//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketWebApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSoru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketSoru()
        {
            this.AnketSeceneklers = new HashSet<AnketSecenekler>();
            this.SecilenCevaplars = new HashSet<SecilenCevaplar>();
        }
    
        public int AnketSoruId { get; set; }
        public int AnketId { get; set; }
        public string Soru { get; set; }
    
        public virtual Anket Anket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketSecenekler> AnketSeceneklers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecilenCevaplar> SecilenCevaplars { get; set; }
    }
}
