//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketWebApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anket()
        {
            this.AnketSorus = new HashSet<AnketSoru>();
            this.SecilenCevaplars = new HashSet<SecilenCevaplar>();
        }
    
        public int AnketId { get; set; }
        public int KonuId { get; set; }
        public string AnketAciklama { get; set; }
        public int OlusturanKullanici { get; set; }
    
        public virtual Konular Konular { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketSoru> AnketSorus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecilenCevaplar> SecilenCevaplars { get; set; }
    }
}
