//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketWebApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecilenCevaplar
    {
        public int SecCevId { get; set; }
        public int SecCevAnketId { get; set; }
        public int SecCevSoruId { get; set; }
        public int SecCevSecenekId { get; set; }
        public int SecCevUyeId { get; set; }
    
        public virtual Anket Anket { get; set; }
        public virtual AnketSecenekler AnketSecenekler { get; set; }
        public virtual AnketSoru AnketSoru { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
